---
name: ((deployment_name)) 

releases:
- name: ((service_release_name))
  version: ((service_release_version))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000
  serial: true

instance_groups:
- name: mariadb
  azs: ((mariadb_azs))
  instances: ((mariadb_instances))
  persistent_disk_type: ((mariadb_persistent_disk_type))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mariadb
    release: ((service_release_name))
    properties:
      database:
        port: ((mariadb_port))
        admin_password: ((mariadb_admin_password))
        broker:
          username: ((mariadb_broker_username))
          password: ((mariadb_broker_password))
  update:
    max_in_flight: 1

- name: service-broker
  azs: ((broker_azs))
  instances: ((broker_instances))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: service-broker
    release: ((service_release_name))
    properties:
      bosh:
        client:
          id: ((bosh_client_id))
          secret: ((bosh_client_secret))
        url: ((bosh_url))
        oauth_url: ((bosh_oauth_url))
        deployment_name: ((deployment_name))
      port: ((broker_port))
      logging:
        level_broker: ((broker_logging_level_broker))
        level_hibernate: ((broker_logging_level_hibernate))
      service:
        admin_password: ((api_gateway_admin_password))
      services:
        id: ((broker_services_id))
        plans:
          id: ((broker_services_plans_id))
  update:
    max_in_flight: 1

- name: api-gateway
  azs: ((api_gateway_azs))
  instances: ((api_gateway_instances))
  persistent_disk_type: ((api_gateway_persistent_disk_type))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  - name: ((public_networks_name))
  jobs:
  - name: api-gateway
    release: ((service_release_name))
    properties:
      service:
        admin_password: ((api_gateway_admin_password))
  update:
    max_in_flight: 1

